export const containsAnySubstring = (
  str1: string,
  str2: string[] = [
    "kid",
    "kids",
    "child",
    "children",
    "kid's",
    "kids'",
    "child's",
    "children's",
    "baby",
    "babies",
    "toddler",
    "toddlers",
    "infant",
    "infants",
    "youngster",
    "youngsters",
    "youth",
    "youths",
    "teen",
    "teens",
    "teenager",
    "teenagers",
    "minor",
    "minors",
    "juvenile",
    "juveniles",
    "preteen",
    "preteens",
    "pre-teen",
    "pre-teens",
    "tween",
    "tweens",
    "pre-schoole",
    "pre-schooler",
    "pre-schoolers",
    "pre-schooler's",
  ],
): boolean => {
  const lowerStr1 = str1.toLowerCase();
  return str2.some((sub) => lowerStr1.includes(sub.toLowerCase()));
};
